name: Landscape2 validate action

inputs:
  target_kind:
    description: 'Kind of file to validate'
    required: true
  target_path:
    description: 'Path of file to validate'
    required: true

runs:
  using: 'docker'
  image: 'docker://public.ecr.aws/g6m3a0y9/landscape2'
  entrypoint: /landscape2-validate.sh
  args:
    - ${{ inputs.target_kind }}
    - ${{ inputs.target_path }}
